# Site settings
title: Synnefo
description: "Synnefo is open source cloud software used to create massively scalable IaaS clouds."
keywords: "cloud software, cloud platform, commodity hardware, large scale, Ganeti, OpenStack, production quality, production ready, okeanos, IaaS" 
baseurl: ""
url: "https://www.synnefo.org"
twitter_username: synnefosoftware
github_repo: grnet/synnefo
google_id: 102978637446585725532

# Build settings
markdown: kramdown
permalink: pretty
exclude: [static/sass/, node_modules, requirements.txt, Gruntfile.js, package.json, README.md]
